### PR TITLE
Implement shared memory WAL.

### PR DESCRIPTION
**Pull request by ncruces**
This intends to implement shared memory WAL for both 64-bit Linux and macOS (`amd64`/`arm64`).

This depends on https://github.com/tetratelabs/wazero/pull/2157 (or some potentially better solution) to ensure Wasm memory is `mmap`ed.

Current solution already passes `mptest` but still needs stability, portability and documentation work.

### CODE REVIEW

**Comment by ncruces** [comment]
Mostly done. Still missing read-only mode, https://github.com/tetratelabs/wazero/pull/2157 improvements, and documentation.

**Comment by ncruces** [comment]
Will need an improved design over https://github.com/tetratelabs/wazero/pull/2157.

**Comment by ncruces** [comment]
This is pretty much ready for testing, @infogulch.

This should also make these binding fully compatible with Litestream, @Koeng101. Suggestions welcome for a Litestream test setup. 

This also opens the way for SQLite [memory mapped IO](https://sqlite.org/mmap.html), and [WAL-Mode Blocking Locks](https://sqlite.org/src/doc/204dbc15a682125c/doc/wal-lock.md).

**Comment by Koeng101** [comment]
I'll test out later! Very exciting!

**Comment by ncruces** [comment]
Windows may be possible after all. For reference:
https://devblogs.microsoft.com/oldnewthing/20240201-00/?p=109346

**Comment by ncruces** [comment]
> It also opens the way for SQLite [memory mapped IO](https://sqlite.org/mmap.html), and [WAL-Mode Blocking Locks](https://sqlite.org/src/doc/204dbc15a682125c/doc/wal-lock.md).

I briefly looked into memory mapped IO, and I won't be pursuing it. It has numerous caveats, especially if not implemented _exactly_ like SQLite does it (mapping the entire file, hoping the size doesn't change often). Trying to implement the API sensibly, leads to a bunch of `syscall`s, memory fragmentation, wasted space. Also not a fan of "crashes on IO errors."

**Pull request merged**
