### PR TITLE
Add ColumnTypeScanType to driver

### LINKED ISSUE #198: Add ColumnTypeScanType to driver
See #197. Continuing here @ngocphuongnb.

For `modernc` you can get new types everytime you call `ColumnTypes()`, and if you call it before the first row, results are undefined. Is this acceptable behavior?

If it isn't, and we really want the type of the column, would it be reasonable to only support this for `STRICT` tables? For those it's totally doable, but some types are impossible (like time, booleans, etc).

If I go by affinity, I'm mostly worried about columns I say are `float64` and there's suddenly a `TEXT`/`BLOB` in them, and `int64` that have fractional numbers. Both can happen, not that it's great database design. Still the affinity rules are complicated: `FLOATING POINT` has `INTEGER` affinity is one example.

I could go with a subset of stricter type names, and argue if you're violating those, your data model sucks. But I really want to test failure modes before commiting.

### PR DESCRIPTION
**Pull request by ncruces**
Fix #198.

### CODE REVIEW

**Comment by ncruces** [comment]
@ngocphuongnb, can you test this please?

**Comment by ncruces** [comment]
I'm gonna merge this as:
1. this passes your [unit test](https://github.com/ncruces/go-sqlite3/pull/197/files#diff-e516710e5f5481513be2a61865cd7e02d8c8aac138cb2c5fae19399d31a992f0)
2. like modernc (which you [linked](https://gitlab.com/cznic/sqlite/-/blob/master/sqlite.go?ref_type=heads#L420-450) to) it supports the following pattern, which I've seen as a common usage

```go
dest := make([]any, len(cols))
for ows.Next() {
	cols, err := rows.ColumnTypes()
	if err != nil {
		return err
	}

	for j, c := range cols {
		dest[j] = reflect.New(c.ScanType()).Interface()
	}

	err = rows.Scan(dest...)
	if err != nil {
		return err
	}
}
```

PR #197 would break this, be it because of "dynamic typing" or just NULLs in any column that's not `[]byte` or `any`.

**Comment by ngocphuongnb** [comment]
@ncruces Thank you for your great effort in making the decision and creating this PR.
The approach with `ColumnTypeScanType` is both creative and thoughtful, addressing the issue in a much more comprehensive and elegant way than my previous solution.
I really appreciate the time and consideration you put into crafting this improvement. Your work makes a significant difference. Thank you again!

**Comment by ncruces** [comment]
Thank you for your kind words!

**Pull request merged**
