### PR TITLE
Steampipe virtual tables.

### PR DESCRIPTION
**Pull request by ncruces**
https://steampipe.io/
https://sqlite.org/forum/forumpost/87a01d8a9f3e51e8

### CODE REVIEW

**Comment by gedw99** [comment]
I also use steam pipe and love the SQL way ...

will try this out for sure..

**Comment by ncruces** [comment]
This one is stalled for complete lack of interest on their part. My issue was ignored; then I pinged their community lead (with whom I'd discussed this on SQLite forum), he tries to rope people in and he is completely ignored.

**Comment by ncruces** [comment]
They have a (1) “plugin” API (in Go) and use those plugins to feed data into (2) virtual tables (in C). I have a (3) pure Go API for virtual tables.

I'd like to plug (1) into (3). Unfortunately (1) is a contrived thing that can, apparently, only communicate with (2) through an obscure gRPC interface. Which is a shame.

I asked for a little help to understand (1) better, but TBH I don't think they're interested. Basically, it'd help me tap into their ecosystem, rather than the opposite, so it makes sense that they just don't care™.

**Comment by gedw99** [comment]
I reckon your hunch is right. It’s a business for them is maybe how they see it ultimately.

**Pull request closed without merging**
